export const siteConfig = {
  name: "As-Sunnah Skill Development Institute",
  nameBn: "আস-সুন্নাহ স্কিল ডেভেলপমেন্ট ইনস্টিটিউট",
  shortName: "As-Sunnah Skill",
  shortNameBn: "আস-সুন্নাহ স্কিল",
  description: "অদক্ষ জনগোষ্ঠীকে কারিগরি বিষয়ে প্রশিক্ষণ প্রদানের মাধ্যমে বেকারত্ব দূরীকরণ ও কর্মসংস্থান সৃষ্টি",
  descriptionEn: "Training unskilled population in technical fields to combat unemployment and create employment opportunities",
  tagline: "দক্ষতায় সমৃদ্ধি, প্রশিক্ষণে ভবিষ্যৎ",
  taglineEn: "Prosperity through Skills, Future through Training",
  url: "https://skill.assunnahfoundation.org",
  founder: "শায়খ আহমাদুল্লাহ",
  founderEn: "Shaykh Ahmadullah",
  parentOrg: "আস-সুন্নাহ ফাউন্ডেশন",
  parentOrgEn: "As-Sunnah Foundation",
  parentOrgUrl: "https://assunnahfoundation.org",
  foundationEstablished: 2017,
  instituteEstablished: 2022,
  established: 2022,
  registration: "জাতীয় দক্ষতা উন্নয়ন কর্তৃপক্ষ (NSDA)",
  registrationEn: "National Skills Development Authority (NSDA)",
  orgType: "অরাজনৈতিক, অলাভজনক ধর্মীয় দাতব্য সংস্থা",
  orgTypeEn: "Non-political, non-profit religious charitable organization",
  logo: "https://cdn.klasio.com/1000017/4140/conversions/assdi-logo-web-logo-(1)-logo.png",
  mission: "মহানবী মুহাম্মদ (সা.)-এর পদাঙ্ক অনুসরণ করে আর্তমানবতার সেবা, সমাজ সংস্কার, কর্মসংস্থান সৃষ্টি, দারিদ্র্য বিমোচন এবং কুরআন ও সুন্নাহ ভিত্তিক জীবন ও সমাজ গঠন করা",
  vision: "বার্ষিক ১,০০,০০০ দক্ষ জনশক্তি তৈরি এবং একটি স্থায়ী ও বৃহৎ প্রশিক্ষণ কেন্দ্র নির্মাণ — যেখানে বছরে ৩০,০০০ প্রশিক্ষণার্থী প্রশিক্ষণ গ্রহণ করতে পারবে",
  contact: {
    phone: "+8809610-001089",
    phone2: "+880 1862-534626",
    email: "skill@assunnahfoundation.org",
    address: "উত্তর বাড্ডা, আলীনগর গেট সংলগ্ন, ঢাকা",
    addressEn: "Uttar Badda, Alinagar Gate, Dhaka",
  },
  social: {
    facebook: "https://facebook.com/assunnahfoundation",
    youtube: "https://youtube.com/@assunnahfoundation",
  },
  stats: {
    totalStudents: 2500,
    totalCourses: 10,
    computerLabs: 7,
    batchesCompleted: 15,
    facilitySqFt: 24000,
    annualGoal: 100000,
  },
  features: [
    "NSDA স্বীকৃত সার্টিফিকেট",
    "সম্পূর্ণ আবাসিক প্রশিক্ষণ",
    "নারী ও পুরুষের জন্য পৃথক ব্যবস্থা",
    "মৌলিক ইসলামি জ্ঞান সহ প্রশিক্ষণ",
    "স্কলারশিপ সুবিধা (সর্বোচ্চ ১০০%)",
    "প্রশিক্ষণ শেষে কর্মসংস্থান সহায়তা",
    "উদ্যোক্তাদের জন্য আর্থিক সহযোগিতা",
    "অভিজ্ঞ প্রশিক্ষক ও ২৪ ঘণ্টা মেন্টর সাপোর্ট",
  ],
};
