export const siteConfig = {
  name: "As-Sunnah Skill Development Institute",
  nameBn: "আস-সুন্নাহ স্কিল ডেভেলপমেন্ট ইনস্টিটিউট",
  shortName: "As-Sunnah Skill",
  shortNameBn: "আস-সুন্নাহ স্কিল",
  description: "দক্ষতা বৃদ্ধি ও আত্মোন্নয়নের প্রতিষ্ঠান — বেকারত্ব দূরীকরণ ও কর্মসংস্থান সৃষ্টি",
  descriptionEn: "Skill development and self-improvement institution — Combating unemployment and creating opportunities",
  tagline: "দক্ষতায় সমৃদ্ধি, প্রশিক্ষণে ভবিষ্যৎ",
  taglineEn: "Prosperity through Skills, Future through Training",
  url: "https://skill.assunnahfoundation.org",
  founder: "শায়খ আহমাদুল্লাহ",
  parentOrg: "আস-সুন্নাহ ফাউন্ডেশন",
  established: 2022,
  registration: "জাতীয় দক্ষতা উন্নয়ন কর্তৃপক্ষ (NSDA)",
  logo: "https://cdn.klasio.com/1000017/4140/conversions/assdi-logo-web-logo-(1)-logo.png",
  contact: {
    phone: "+8809610-001089",
    phone2: "+880 1862-534626",
    email: "skill@assunnahfoundation.org",
    address: "উত্তর বাড্ডা, আলীনগর গেট সংলগ্ন, ঢাকা",
    addressEn: "Uttar Badda, Alinagar Gate, Dhaka",
  },
  social: {
    facebook: "https://facebook.com/assunnahfoundation",
    youtube: "https://youtube.com/@assunnahfoundation",
  },
  stats: {
    totalStudents: 2500,
    totalCourses: 20,
    computerLabs: 7,
    batchesCompleted: 15,
    facilitySqFt: 24000,
  },
};
